excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://iambetmen.github.io
title: ./iambetmen
email: betmen@protonmail.ch
author: &#1074;&#1108;&#1090;&#1084;&#1108;&#951;
description: My Experience
paginate: 5
google_analytics: 