excerpt_separator: ""
pygments: true
markdown: kramdown
url: https://iambetmen.github.io/
title: ./iambetmen
email: betmen@protonmail.ch
author: iambetmen
description: My Experience
paginate: 5
google_analytics: 